[config]
reload_apps = true
reload_apps_list = ["waybar"]

[config.reload]
waybar = "killall -SIGUSR2 waybar"

[templates.waybar-colors]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/theme.css"
