include current-theme.conf

enable_wayland yes

repaint_delay 8
input_delay 1
sync_to_monitor yes

shell zsh

clipboard_control write-clipboard write-primary

enable_audio_bell no
visual_bell_duration 0.0

remember_window_size yes
initial_window_width  900
initial_window_height 600
window_padding_width 5

font_family JetBrainsMono Nerd Font
font_size 12
bold_font auto
italic_font auto
bold_italic_font auto

cursor_blink_interval 0.5
cursor_stop_blinking_after 1
scrollback_lines 2000
wheel_scroll_min_lines 1

background_opacity 0.7
dynamic_background_opacity yes
confirm_os_window_close 0
cursor_trail 1
