source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/rules.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/exec.conf

# HyprEmoji config
source = ~/.config/hypremoji/hypremoji.conf
