# This file is auto-generated by zpm
# Last updated: 2026-03-04 12:46:31
# User: navithecoderboi

# Plugin: zsh-autosuggestions
source "/home/navithecoderboi/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"

# Plugin: zsh-completions
source "/home/navithecoderboi/.config/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh"

# Plugin: zsh-syntax-highlighting
source "/home/navithecoderboi/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"

