general {
    gaps_in = 10
    gaps_out = 16
    border_size = 0
    layout = dwindle
    resize_on_border = true

    col.active_border = 0xff7eadaa
    col.inactive_border = 0xff1a201e
    col.nogroup_border = 0xffffaaff
    col.nogroup_border_active = 0xffff00ff
}
