# custom float window
windowrule {
    name = float-term
    match:class = ^(float-term)$    
    float = on
    center = on
    size = 900 550
}

# Satty
windowrule {
    name = satty
    match:class = com.gabm.satty
    float = true
    center = true
    size = 900 700
}

# NmGui
windowrule {
    name = nmgui
    match:class = ^(nmgui)$
    float = true
    center = true
    size = 900 800
}

# Pavucontrol
windowrule {
    name = pavucontrol
    match:class = (.*org.pulseaudio.pavucontrol.*)
    float = true
    center = true
    pin = true
    size = 700 600
}

# Waypaper
windowrule {
    name = waypaper
    match:class = (.*waypaper.*)
    float = true
    center = true
    pin = true
    size = 900 700
}

# nwg-look
windowrule {
    name = nwg-look
    match:class = (nwg-look)
    float = true
    center = true
    size = 700 600
}

# nm-connection-editor
windowrule {
    name = nm-connection-editor
    match:class = (nm-connection-editor)
    float = true
    center = true
    size = 800 700
}

# Picture-in-Picture
windowrule {
    name = Picture-in-Picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = true
    pin = true
    center = true
}
